num_1 = int(input())
num_2 = int(input())
num_3 = int(input())
num_4 = int(input())
num_5 = int(input())
num_6 = int(input())
num_7 = int(input())

print(num_1)
print(num_2)
print(num_3)
print(num_4)
print(num_5)
print(num_6)
print(num_7)
